# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the
# server process.

# Basic Site Settings
locale: "en-US"
site_theme: "default"
title: "Nicole Lillian Mark"
title_separator: "-"
name: &name "Nicole Lillian Mark"
description: &description "Information designer, storyteller, engineer"
url: https://nicolelily.github.io # the base hostname & protocol for your site e.g. "https://[your GitHub username].github.io" or if you already have some other page hosted on GitHub then use "https://[your GitHub username].github.io/[Your Repo Name]"
baseurl: "" # the subpath of your site, e.g. "/blog"
repository: "nicolelily/nicolelily.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#             If a field is blank the icon and link will not appear, otherwise it will be shown.
#             Additional customization can be done by editing `_includes/author-profile.html`
author:
  # Biographic information
  avatar: "new-avataaars-red-hair-transparent.png"
  name: "Nicole Lillian Mark"
  pronouns: "she/her"
  bio: "Information designer 👩‍💻 Dog mom 🐶 Vegan for the animals 🌱"
  location: "United States"
  employer: "Nicole Designs Data LLC"
  uri: # URL
  email: "nicoledesignsdata@pm.me"

# Academic websites
  academia: # URL
  arxiv: # URL
  googlescholar: # URL
  inspire-hep: # URL
  impactstory: # URL
  orcid: "https://orcid.org/0000-0001-8383-274X"
  semantic: # URL
  pubmed: # URL
  researchgate: # URL
  scopus: "https://www.scopus.com/authid/detail.uri?authorId=57208165220"

# Repositories and software development
  bitbucket: # Username - Update with your username on the site
  codepen: "nicoledesignsdata"
  dribbble: "nicoledesignsdata"
  github: "nicolelily"
  kaggle: # Username
  stackoverflow: "13801278/nicole-mark"

# Social media
  artstation: # Username
  bluesky: "nicoledesignsdata.com" # Replace this with you Bluesky username
  facebook: "nicoledesignsdata"
  flickr: # Username
  foursquare: # Username
  goodreads: # Username
  google_plus: # Username
  keybase: # Username
  instagram: "nicoledesignsdata"
  lastfm: # Username
  linkedin: "nicole-mark"
  mastodon: # URL
  medium: "https://medium.com/@nicolemark"
  pinterest: # Username
  soundcloud: # Username
  spotify: # Username
  steam: # Username
  tumblr: # Username
  twitter: "@nicolemark_"
  youtube: # Username
  patreon: # Username
  paypal: # Username
  strava: # Username
  telegram: # Username
  whatsapp: # Username

# Site Settings
analytics:
  provider: "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id: "G-1WJ20P92R1"
    anonymize_ip: # true, false (default)

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-plantuml

# mimic GitHub Pages with remote_theme
remote_theme: academicpages/academicpages.github.io@409640ac6b50a6b52d50a328c3d722874337322a

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: "" # an empty string here means all files in the project
      type: "portfolio"
    values:
      layout: "single"
      author_profile: true
      share: true
  # _publications
  - scope:
      path: "" # an empty string here means all files in the project
      type: "publications"
    values:
      layout: "single"
      author_profile: true
      share: true

# Front matter defaults
---



