project:
  type: website
  output-dir: docs

website:
  title: "Nicole Mark"
  navbar:
    search: true
    logo: "https://i.postimg.cc/5NrTmpx7/Nicole-Designs-Data-new-logo-white-background.png"
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



